name: lonate
description: A super effective Dart and Flutter library for delivering performante app & ensuring greater build speed.
version: 0.0.2
homepage: https://github.com/Rexfordasamoah51/Lonate

environment:
  sdk: ">=2.14.4 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
