name: lonate
description: A super effective Dart and Flutter library for delivering performante app & ensuring greater build speed.
version: 0.0.2
homepage: https://github.com/Rexfordasamoah51/Lonate

environment:
  sdk: ">=2.14.4 <3.0.0"


dev_dependencies: 
  lints: ^2.0.1
  test: ^1.22.0

# The following section is specific to Flutter.
flutter:
