name: LonateTest
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.7.0-3.1.pre"
          channel: "beta"
      - name: Install app dependencies
        run: flutter pub get
      - name: Test app
        run: flutter test --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: b937c2d2-d81f-4f88-b06a-6ba2f07eeab0
          file: coverage/lcov.info
